<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>CreatureProbe\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\undertalemodtool-src\UndertaleModLib\UndertaleModLib.csproj" />
    <ProjectReference Include="..\undertalemodtool-src\Underanalyzer\Underanalyzer\Underanalyzer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="hooker\src\**\*.cs" />
    <Content Remove="assets\**\*" />
    <None Remove="assets\**\*" />
  </ItemGroup>
  <Target Name="CopyAssets" AfterTargets="CopyFilesToOutputDirectory">
    <ItemGroup>
      <Assets Include="assets/**/*.*" />
    </ItemGroup>
    <RemoveDir Directories="$(TargetDir)/assets;$(TargetDir)/code;$(TargetDir)/data;$(TargetDir)/included;$(TargetDir)/sounds;$(TargetDir)/sprites"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(TargetDir)/assets/%(RecursiveDir)" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CopyIncludes" AfterTargets="AfterBuild">
    <ItemGroup>
      <Assets Include="IncludedFiles/**/*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(TargetDir)/%(RecursiveDir)" SkipUnchangedFiles="false" />
  </Target>
  <Target Name="CleanDuplicateAssetRoots" AfterTargets="Build">
    <RemoveDir Directories="$(TargetDir)/code;$(TargetDir)/data;$(TargetDir)/included;$(TargetDir)/sounds;$(TargetDir)/sprites"/>
  </Target>
</Project>
